<a href="https://colab.research.google.com/github/Gulayrose/statistics/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [2]:
arr_2d[0,2]

15

In [3]:
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1)-np.max(arr_2)

array([-4., -3., -2., -1.,  0.])

In [4]:
np.sqrt(arr_1)

array([2., 3., 4., 5., 6.])

In [5]:
np.max(arr_2)

6

In [6]:
arr=np.arange(1,37)
arr.shape

(36,)

In [7]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [9]:
arr_2d[:1,1:]

array([[10, 15]])